baseurl: '/'
permalink: pretty
title: 'GVC Lab'

logo:
  mobile: "images/logo/gbugvc.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/gbugvc.png"
  desktop_height: "48px"

home: 
  limit_services: 3
  limit_news: 6

collections:
  researches:
    output: true
    sort_by: weight
  team:
    output: true
  seminar:
    output: true

defaults:
  - scope:
      path: ""
      type: "researches"
    values:
      layout: "research"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"
  - scope:
      path: ""
      type: "seminar"
    values:
      layout: "seminar"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
